""" 
Django settings for wajeloyality project. 
Generated by 'django-admin startproject' using Django 2.0.7. 
For more information on this file, see https://docs.djangoproject.com/en/2.0/topics/settings/ 
For the full list of settings and their values, see https://docs.djangoproject.com/en/2.0/ref/settings/ 
"""

import os
import datetime
from datetime import timedelta
from django.conf import settings
from decouple import config

Temp_Path = os.path.realpath('.')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# wkhtmltopdf path
WKHTMLTOPDF_PATH = config('WKHTMLTOPDF_PATH', default=os.path.join(BASE_DIR, 'wkhtmltopdf', 'bin', 'wkhtmltopdf.exe'))

# Environment mode
ENVIRONMENT = config('DJANGO_ENV', default='development')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='secret_key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SETTINGS_PATH = settings.BASE_DIR

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

APP_URL = 'https://wajeloyality.website'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'safedelete',
    'wajecrm.apps.WajecrmConfig',
    'corsheaders',
    'django.contrib.humanize',
    # 'drf_yasg',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
]

ROOT_URLCONF = 'wajecrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_DIRS = (
    os.path.join(SETTINGS_PATH, 'campaigntemplates'),
)

WSGI_APPLICATION = 'wajeloyality.wsgi.application'

# Database routers
DATABASE_ROUTERS = ['wajecrm.router.WajeRouter']
DATABASE_APPS_MAPPING = {
    'mpos0': 'loyalty',
    'DST': 'midas',
}

import sys

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='your_db_name'),
        'USER': config('DB_USER', default='your_db_user'),
        'PASSWORD': config('DB_PASSWORD', default='password'),
        'HOST': config('DB_HOST', default='host'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'init_command': "SET SESSION sql_mode='STRICT_TRANS_TABLES'",
        },
    },
    # 'loyalty': {
    #     'ENGINE': 'sql_server.pyodbc',
    #     'NAME': config('LOYALTY_DB_NAME', default='your_db_name'),
    #     'USER': config('LOYALTY_DB_USER', default='your_db_name'),
    #     'PASSWORD': config('LOYALTY_DB_PASSWORD', default='your_db_password'),
    #     'HOST': config('LOYALTY_DB_HOST', default='your_db_host'),
    #     'PORT': config('LOYALTY_DB_PORT', default='1433'),
    #     'OPTIONS': {
    #         'driver': config('LOYALTY_DB_DRIVER', default='driver'),
    #         'unicode_results': True,
    #         'host_is_server': True,
    #         'autocommit': True,
    #         'extra_params': 'tds_version=7.3;',
    #     },
    }
}

# Use SQLite for testing
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'wajecrm.utils.auth.CustomJWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Waje Loyality API',
    'DESCRIPTION': 'To generate and sale gift cards',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Email configuration
EMAIL_HOST = 'web.ipnxng.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'noreply@wajesmart.com'
EMAIL_HOST_PASSWORD = 'cZlIvb}*ET!M'
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = ''

# JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=720),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': settings.SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Static and media files
STATIC_URL = '/static/'
MEDIA_URL = '/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

FILE_UPLOAD_HANDLERS = (
    "django_excel.ExcelMemoryFileUploadHandler",
    "django_excel.TemporaryExcelFileUploadHandler",
)
