"""
Django settings for wajeloyality project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import datetime
from datetime import timedelta
from django.conf import settings
import pymysql
import os.path
from decouple import config


Temp_Path = os.path.realpath('.')

#pymysql.install_as_MySQLdb()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Environment mode
ENVIRONMENT = config('DJANGO_ENV', default='development')

DEFAULT_AUTO_FIELD='django.db.models.BigAutoField'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('$)qsyduv4a!ft%7xwjcw4-iodc$_#uu4%ssps)0l=vg@ic(y5r', default="secret_key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['199.192.28.167',
                 'wajeloyality.website', 'localhost', '127.0.0.1', 
                 'wajeloyalityapitest.onrender.com',
                 'wajeloyalityapitest-2.onrender.com']

SETTINGS_PATH = settings.BASE_DIR

APP_URL='https://wajeloyality.website'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'safedelete',
    'wajecrm.apps.WajecrmConfig',
    'corsheaders',
    'django.contrib.humanize',
    # 'drf_yasg'
    'drf_spectacular'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
 ]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'wajecrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_DIRS = (
    os.path.join(SETTINGS_PATH, 'campaigntemplates'),
)

WSGI_APPLICATION = 'wajeloyality.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

''' DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
} '''
DATABASE_ROUTERS = ['wajecrm.router.WajeRouter']
DATABASE_APPS_MAPPING = {'mpos0': 'loyalty',
                         'DST': 'midas',
                         }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.' + config('DB_ENGINE', default='postgresql'),  # Dynamic engine selection
        'NAME': config('DB_NAME', default='wajeloyaltycrmdb'),
        'USER': config('DB_USER', default='your_db_user'),
        'PASSWORD': config('DB_PASSWORD', default='your_db_password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
    },

}

if ENVIRONMENT == 'production':
    DATABASES['loyalty'] = {
        'ENGINE': 'django.db.backends.' + config('DB_ENGINE', default='mssql'),
        'NAME': config('DB_NAME', default='prod_database'),
        'USER': config('DB_USER', default='prod_user'),
        'PASSWORD': config('DB_PASSWORD', default='prod_password'),
        'HOST': config('DB_HOST', default='prod_server'),
        'PORT': config('DB_PORT', default='1433'),
        'OPTIONS': {'driver': 'ODBC Driver 17 for SQL Server'},
    }


    

        
    

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS':
    'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 30
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Waje Loyality API',
    'DESCRIPTION': 'To generate and sale gift cards',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
'''
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_HOST_USER ='cozigbo@wajesmart.com'
EMAIL_HOST_PASSWORD ='Chi@1234!'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = '<cozigbo@wajesmart.com>'
'''
EMAIL_HOST = 'web.ipnxng.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'noreply@wajesmart.com'
EMAIL_HOST_PASSWORD = 'cZlIvb}*ET!M'
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = '<noreply@wajesmart.com>'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=720),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': settings.SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")
