# Generated by Django 2.1.5 on 2019-02-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('merchID', models.CharField(max_length=45)),
                ('campaigntype', models.CharField(max_length=45)),
                ('interval', models.CharField(max_length=100)),
                ('tempateID', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=1)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
        ),
        migrations.CreateModel(
            name='campaignTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('body', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=1)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('emailaddress', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('customerIdentifier', models.CharField(max_length=45)),
                ('addressdetails', models.CharField(max_length=45)),
                ('facebooklink', models.CharField(max_length=45, null=True)),
                ('twitterlink', models.CharField(max_length=45, null=True)),
                ('instagramlink', models.CharField(max_length=45, null=True)),
                ('DOB', models.DateField(null=True, verbose_name='date_of_birth')),
                ('active', models.BooleanField(default=1)),
                ('merchID', models.IntegerField()),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
        ),
        migrations.CreateModel(
            name='loyaltyrule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyaltyrule', models.CharField(max_length=45)),
                ('rewardpoint', models.CharField(max_length=45, null=True)),
                ('amountspent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('startdate', models.DateField(null=True, verbose_name='createddate')),
                ('endate', models.DateField(null=True, verbose_name='updateddate')),
                ('merchID', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
        ),
        migrations.CreateModel(
            name='loyaltyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyaltyruleID', models.IntegerField(null=True)),
                ('CustID', models.IntegerField(null=True)),
                ('merchID', models.IntegerField()),
                ('receiptno', models.CharField(max_length=100, unique=True)),
                ('transactionamount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('assignedpoint', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('transactiondate', models.DateField(null=True, verbose_name='transctiondate')),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
        ),
        migrations.CreateModel(
            name='merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.CharField(max_length=45, null=True)),
                ('merchantphonenumber', models.CharField(max_length=45, null=True)),
                ('businessaddress', models.CharField(max_length=45, null=True)),
                ('merchantemailaddress', models.CharField(max_length=45, null=True)),
                ('merchantpassword', models.CharField(max_length=255, null=True)),
                ('contactpersonfirstname', models.CharField(max_length=255, null=True)),
                ('contactpersonlastname', models.CharField(max_length=255, null=True)),
                ('businesslogo', models.ImageField(upload_to='merchantlogo/')),
                ('active', models.BooleanField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('settingsactivated', models.BooleanField(default=0)),
                ('businessdescription', models.CharField(max_length=255, null=True)),
                ('businessfacebook', models.CharField(max_length=45, null=True)),
                ('businesstwitter', models.CharField(max_length=45, null=True)),
                ('bankname', models.CharField(max_length=255)),
                ('accountnumber', models.CharField(max_length=255)),
                ('accountname', models.CharField(max_length=255)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
            options={
                'ordering': ['serviceID'],
            },
        ),
    ]
