# Generated by Django 3.2.9 on 2025-03-21 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cardName', models.CharField(max_length=200)),
                ('confirmationCode', models.CharField(max_length=20, unique=True)),
                ('transactionRef', models.CharField(max_length=255, unique=True)),
                ('dateConfirmed', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.CharField(max_length=200)),
                ('datePayment', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('auditor', 'Auditor'), ('manager', 'Manager')], default='admin', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wajecrm.role'),
        ),
    ]
