# Generated by Django 2.1.5 on 2019-02-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
