# Generated by Django 4.2.19 on 2025-03-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='reference',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
