# Generated by Django 2.1.5 on 2019-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0002_auto_20190214_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntemplate',
            name='merchID',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='body',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
