# Generated by Django 4.2.19 on 2025-03-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0002_alter_giftcardtransaction_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='deleted_by_cascade',
        ),
    ]
