# Generated by Django 2.1.5 on 2019-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0003_auto_20190214_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntemplate',
            name='body',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
