# Generated by Django 2.1.5 on 2019-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0004_auto_20190214_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaignhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantname', models.CharField(max_length=45)),
                ('customeremail', models.CharField(max_length=255, null=True)),
                ('campaigntype', models.CharField(max_length=255, null=True)),
                ('templatename', models.CharField(max_length=45, null=True)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
        ),
    ]
