# Generated by Django 3.2.9 on 2025-03-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
