# Generated by Django 2.1.5 on 2019-02-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0006_campaignhistory_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignhistory',
            name='merchID',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
