# Generated by Django 2.1.5 on 2019-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0007_campaignhistory_merchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='contactpersonphone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
