# Generated by Django 2.1.5 on 2019-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0008_merchant_contactpersonphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='businessname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='campaignhistory',
            name='createddate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='createddate'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='createddate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='createddate'),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='createddate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='createddate'),
        ),
    ]
