# Generated by Django 2.1.5 on 2019-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0009_auto_20190220_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
