# Generated by Django 2.1.5 on 2019-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0010_auto_20190220_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='serviceID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
