# Generated by Django 2.1.5 on 2019-02-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0011_auto_20190226_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='serviceID',
            field=models.IntegerField(null=True),
        ),
    ]
