# Generated by Django 2.1.5 on 2019-02-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0012_auto_20190226_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='serviceID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
