# Generated by Django 2.1.5 on 2019-02-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0013_auto_20190226_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
