# Generated by Django 2.1.5 on 2019-02-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0014_merchant_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignhistory',
            name='merchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='merchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='merchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='merchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
        migrations.AlterField(
            model_name='loyaltyrule',
            name='merchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='CustID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.customer'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='loyaltyruleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.loyaltyrule'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='merchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
    ]
