# Generated by Django 2.1.5 on 2019-03-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0017_auto_20190307_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='themebordercolor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='themecolor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='themecolorlight',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='themetextcolor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='themetitlecolor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
    ]
