# Generated by Django 2.2.1 on 2019-06-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0018_auto_20190325_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='transactionpin',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
    ]
