# Generated by Django 2.1.10 on 2019-07-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0020_auto_20190717_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignhistory',
            name='campaign_channel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='country_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emailaddress',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='assignedpoint',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
