# Generated by Django 2.1.10 on 2019-07-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0022_auto_20190728_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='country_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
    ]
