# Generated by Django 2.1.10 on 2019-08-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0024_auto_20190805_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=45)),
                ('branchaddress', models.CharField(max_length=45, null=True)),
                ('branchstate', models.CharField(max_length=45, null=True)),
                ('branchcity', models.CharField(max_length=45, null=True)),
                ('branchofficeline', models.CharField(max_length=45, null=True)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
        ),
        migrations.CreateModel(
            name='branchmanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managername', models.CharField(max_length=45)),
                ('managerusername', models.CharField(max_length=45, null=True)),
                ('managerpassword', models.CharField(max_length=255, null=True)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
                ('branchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.branch')),
            ],
        ),
        migrations.CreateModel(
            name='crosscampaignrule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignrulename', models.CharField(max_length=45)),
                ('item', models.ImageField(null=True, upload_to='crosspromotion/')),
                ('amountspent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('startdate', models.DateField(null=True, verbose_name='createddate')),
                ('endate', models.DateField(null=True, verbose_name='updateddate')),
                ('status', models.BooleanField(default=1)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
            ],
        ),
        migrations.CreateModel(
            name='tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiermerchantname', models.CharField(max_length=200, null=True, unique=True)),
                ('numberofpoints', models.CharField(max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='campaignstatus',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='pointname',
            field=models.CharField(default='point', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tier',
            name='merchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
        migrations.AddField(
            model_name='tier',
            name='tiername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.plan'),
        ),
        migrations.AddField(
            model_name='crosscampaignrule',
            name='merchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
        migrations.AddField(
            model_name='branchmanager',
            name='merchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
        migrations.AddField(
            model_name='branch',
            name='merchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant'),
        ),
    ]
