# Generated by Django 2.1.10 on 2019-08-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0025_auto_20190827_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='recipient_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='reference',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
    ]
