# Generated by Django 2.1.10 on 2019-09-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0027_auto_20190903_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
    ]
