# Generated by Django 2.1.10 on 2019-09-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0028_auto_20190904_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='created_at',
            new_name='createddate',
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
    ]
