# Generated by Django 2.1.10 on 2019-09-19 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0029_auto_20190904_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branchcode',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='receiptno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
