# Generated by Django 2.1.10 on 2019-12-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0031_auto_20191114_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45, null=True)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
                ('merchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45, null=True)),
                ('userpassword', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=255, null=True)),
                ('createddate', models.DateField(auto_now_add=True, verbose_name='createddate')),
                ('updateddate', models.DateField(null=True, verbose_name='updateddate')),
                ('branchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.branch')),
                ('merchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.merchant')),
            ],
        ),
        migrations.RemoveField(
            model_name='branchmanager',
            name='branchID',
        ),
        migrations.RemoveField(
            model_name='branchmanager',
            name='merchID',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='createdby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='giftcardtransaction',
            name='createdby',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
        migrations.DeleteModel(
            name='branchmanager',
        ),
    ]
