# Generated by Django 2.1.10 on 2020-01-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0034_auto_20191216_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='transactionamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=60, null=True),
        ),
    ]
