# Generated by Django 2.1.10 on 2020-02-03 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0035_auto_20200115_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
    ]
