# Generated by Django 2.1.15 on 2021-11-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0036_auto_20200203_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='tempateID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wajecrm.campaigntemplate'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number_of_license',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='serialnumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='initial_minimum_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='numberofpoints',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='tiermerchantname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
