# Generated by Django 3.2.9 on 2021-11-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0037_auto_20211125_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
