# Generated by Django 3.2.9 on 2024-02-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0038_giftcard_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='deleted',
            field=models.DateField(null=True, verbose_name='deleted'),
        ),
    ]
