# Generated by Django 4.2.19 on 2025-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0039_alter_giftcard_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
