# Generated by Django 3.2.9 on 2025-04-03 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0040_auto_20250403_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wajecrm.role'),
        ),
    ]
