# Generated by Django 4.2.19 on 2025-02-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0040_giftcard_deleted_by_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='AccountantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cardname', models.CharField(max_length=200)),
                ('confirmationCode', models.CharField(editable=False, max_length=20, unique=True)),
                ('transactionRef', models.CharField(max_length=255)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wajecrm.giftcard')),
            ],
        ),
    ]
