# Generated by Django 4.2.19 on 2025-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0041_alter_giftcard_deleted_accountantdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantdata',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='accountantdata',
            name='dateConfirmed',
            field=models.DateField(null=True),
        ),
    ]
