# Generated by Django 3.2.9 on 2025-04-03 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0042_copy_role_to_role_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='createdby_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wajecrm.user'),
        ),
    ]
