# Generated by Django 4.2.19 on 2025-02-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0042_accountantdata_customer_accountantdata_dateconfirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountantdata',
            name='giftcard',
        ),
    ]
