# Generated by Django 4.2.19 on 2025-02-27 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0043_remove_accountantdata_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountantdata',
            name='datePayment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accountantdata',
            name='customer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accountantdata',
            name='dateConfirmed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
