# Generated by Django 3.2.9 on 2025-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0044_populate_createdby_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcard',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
