# Generated by Django 4.2.19 on 2025-02-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0044_accountantdata_datepayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountantdata',
            old_name='cardname',
            new_name='cardName',
        ),
    ]
