# Generated by Django 4.2.19 on 2025-03-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0045_rename_cardname_accountantdata_cardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='settingsactivated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='themecolor',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
