# Generated by Django 3.2.9 on 2025-04-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0045_auto_20250403_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcard',
            old_name='createdby_fk',
            new_name='createdby',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_fk',
            new_name='role',
        ),
    ]
