# Generated by Django 4.2.19 on 2025-03-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0046_alter_merchant_settingsactivated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
