# Generated by Django 4.2.19 on 2025-03-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0047_alter_merchant_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='active',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='settingsactivated',
            field=models.BooleanField(default=0),
        ),
    ]
