# Generated by Django 4.2.19 on 2025-03-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0048_alter_merchant_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='settingsactivated',
            field=models.BooleanField(default=1),
        ),
    ]
