# Generated by Django 4.2.19 on 2025-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0049_alter_merchant_settingsactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountantdata',
            name='transactionRef',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
