# Generated by Django 4.2.19 on 2025-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0050_alter_accountantdata_transactionref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountantdata',
            name='confirmationCode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
