# Generated by Django 4.2.19 on 2025-03-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wajecrm', '0051_alter_accountantdata_confirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountantdata',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
