name: VPS-Autodeploy
on:
  # any code pushed to production branch will be a trigger
  push:
    branches:
      - production

# jobs definition
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🍏 Checking out"
      - name: Checkout code
        uses: actions/checkout@v3

      - run: echo "🔎 Deploy to Giftcard Server"

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.SSH_CODE_PATH }}

      - run: echo "✅ Code pushed to VPS ✅ ${{ job.status }}."

      - run: echo "♻️ Completed Successfully  🌀 ${{ job.status }}."
      - run: echo "🍏 This job's status is ${{ job.status }}."